### ISSUE TITLE
表示こわれてるマークダウンを直す

### ISSUE THREAD

**Issue by nanaka0012** [enpitut2020/Hobeeeeee#10]
## 概要

記事作成画面のマークダウンエディターの表示がなぜかバグってるのでそれを直す
![image](https://user-images.githubusercontent.com/50493355/99136464-46ba4980-2668-11eb-91ea-1d7d95c0e4c6.png)

## 関連issue

PBL: #8

**Comment by mei28** [comment]
#25 で対応したよ
