### ISSUE TITLE
復旧後のタグで名前を修正したやつが修正しきれてない

### ISSUE THREAD

**Issue by nanaka0012** [enpitut2020/Hobeeeeee#112]
## 概要

Relevanceの中にあるほう修正するの忘れてたね
![image](https://user-images.githubusercontent.com/50493355/105060522-d8f12a80-5abb-11eb-97fd-ee34de3e8284.png)

**Comment by Kattsuuya** [comment]
こりゃ大変だ😱

**Comment by Kattsuuya** [comment]
Done!
