### ISSUE TITLE
firebaseのデータ構造を決める

### ISSUE THREAD

**Issue by mei28** [enpitut2020/Hobeeeeee#12]
## 概要

- **複数人でやる**
- firebaseと組み合わせる時のデータ構造の決定
- 記事を書く際，記事を見る際の2つで共通するデータから考える．
- まずは必要なデータだけで進めるのはあり，（追加したあと機能実装をまたやるか大変かもしれない）
- のちのち使うきのう(e.g. ずぶったボタン)とかはここで考えてもいいし，後回しでもいい？

## 関連issue

PBL: #8

**Comment by ryogo-niwa** [comment]
**①Hobbyのデータ構造**
関連趣味をサブコレクションに分けたほうがいいかも？って思いました！
hobbies/hobbyA/relative_hobbees/relative_hobbyA
hobbies/hobbyA/relative_hobbees/relative_hobbyB
→ノードの重み更新の時に少し楽かも

ref = db.collection(hobbies).document(“hobbyA”).collection(relative_hobbees).document(“relativeHobbyA)
ref.update(“weight”, firebase.firestore.FieldValue.increment(1));

→現時点だと、関連趣味がhobbyAドキュメントの配列の中に存在していて、配列の中のインクリメントは少し複雑な予感がしたので！


**②Commentを記事データのサブコレクションに分けるか、記事データの配列に入れるか**
→取得の時に楽ができそうだから、配列の方が良いかも？って思いました

articleRef = db.collectoin(“hobbees”).document(“hobbyA”).collection(“articles”).document(“article1)
articleRef(getOptions).then(function(doc) {
    articleData = doc.data()
    commentArray = articleData[“comments”]
})
多分こんな感じ！

**③Article必要最低限データ構造ざっくり書いてみた**
hobbees/hobbyA/articles/article1（hobbyA１つ目の記事)
hobbees/hobbyA/articles/article2(hobbyA２つ目の記事)
{
title: “タイトル(必須)”,
content: “記事内容(必須)”,
created_at: 
comments: [“ありがとうございます！沼にはまりました！”,”いい記事です!”]
}

**Comment by Kattsuuya** [comment]
@niwabarubossa 
created_atって執筆者ってことだよね？

**Comment by mei28** [comment]
記事のidじゃない？

**Comment by Kattsuuya** [comment]
案1：先にカテゴライズ （現時点での実装方針）
```
/hobbies/[hobby]/articles/[article]
/hobbies/[hobby]/relativeHobbies/[relativeHobby]
```

```
hobby
{
  id: String,
  name: String,
  volume: Integer, // 規模、記事数とかから算出？
}
```

```
article
{
  id: String,
  title: String,
  body: String,
  createdBy: String,
  createdAt: Date,
  updatedAt: Date,
}
```

```
relativeHobby
{
  id: String,
  name: String,
  relevance: Integer, // 関連度、weightのこと？
}
```

案2：タグで後から集計
ここで言うタグは趣味のカテゴリとほぼ同義

```
/articles/[article]
/tags/[tag]
```

```
article
{
  id: String,
  title: String,
  body: String,
  createdBy: String,
  createdAt: Date,
  updatedAt: Date,
  tags: [{ // タグの配列
    id: String,
  }]
}
```

```
tag
{
  id: String,
  name: String,
  relative: [{ // 関連するタグの配列
    id: String,
    relevance: Integer,  // 関連度
  }],
}
```

案1「先にカテゴライズ」の
メリット
実装量が少ない（用意した趣味だけで考えれば関連や規模感がすぐに計算できる）
デメリット
1つの記事に複数の趣味を付与できない（サッカー AND フットサルみたいなのができない）
新しい趣味を追加できない

案2「後からタグで集計」の
メリット
趣味を増やせる（新しいノードができる）
分類する手間が省ける（とりあえず"記事"としてまとめておける）
デメリット
1つの記事をどの趣味のノードとして表示するかを考える必要がある
集計する処理が増える

**Comment by hotsukai** [comment]
自分は @niwabarubossa と@KindMapleの案1に完全同意!!
@KindMapleの言うように一つの記事が複数の趣味カテゴリを保つ場合のベストプラクティスはかつやさんのいう案2だと思うんだけど、
- 複数の趣味カテゴリ持つのが限定的
- NoSQLでそれをやるのは作業量が増える
- firestoreへのアクセス数がやたら増える(50000件制限がこわい)
からそこまでヤラなくていいんじゃないかと思った。

**Comment by mei28** [comment]
案2をすこしやってみて，時間かかりそうだったら中断して，案1にしよう

**Comment by nanaka0012** [comment]
そういえば、案2にしたことで増えてそうなSBLとそれに対応したissueも考えないとだね

**Comment by ryogo-niwa** [comment]
変更前

```
tag
{
  id: String,
  name: String,
  relative: [{ // 関連するタグの配列
    id: String,
    relevance: Integer,  // 関連度
  }],
}
```



変更後
```
tags/MRyks
{
  id: MRyks,
  name: フットサル,
 volume: Number.
},
tags/iYnTc
{
  id: iYnTc,
  name: バスケットボール,
 volume: Number.
}
```

**Comment by ryogo-niwa** [comment]
名前入れたほうが後々良さそうと感じた！

フットサルの関連趣味はバスケであることを示す。関連度15
```
tags/MRyks/relative/iYnTc
{
  id: iYnTc,
  name: "バスケットボール",
  relevance: 15,
}
```

バスケの関連趣味はフットサルであり、関連度15であることを示す。
```
tags/iYnTc/relative/MRyks
{
  id: MRyks,
  name:"フットサル",
  relevance: 15,
}
```

**Comment by Kattsuuya** [comment]
idを参照すればタグ名は取得できるから必要ないと思う！

**Comment by nanaka0012** [comment]
確か、NoSQLだとId取得してからnameを取得して…ってなっちゃうから入れるのもアリって話を昨日canvas組でしてたので、入れてもいいかもしれない😶

**Comment by Kattsuuya** [comment]
なるほど理解！
関連趣味をグラフ描画するときに必要な情報は予めrelativeコレクションに入れたほうがいいってこと？

**Comment by ryogo-niwa** [comment]
僕もその理解です！
データの取得回数を減らすための冗長性って感じかと！

**Comment by hotsukai** [comment]
これ、今の設計だとあるタグ(たとえばスポーツ)の記事一覧取ってくることができない気がする。
治すためには、タグのサブコレクションかフィールドに記事のIDの集合を保存しとく必要があると思う。

**Comment by hotsukai** [comment]
@KindMaple @niwabarubossa 
グラフ描画のための情報は入れちゃったほうが描画は楽だけど、
そうするとVolumeも入れないといけないからそこは要検討かも

**Comment by ryogo-niwa** [comment]
>これ、今の設計だとあるタグ(たとえばスポーツ)の記事一覧取ってくることができない気がする。
治すためには、タグのサブコレクションかフィールドに記事のIDの集合を保存しとく必要があると思う。

確かに！！記事ドキュメントにこんな感じで追加かな
```
article
{
  id: String,
  title: String,
  body: String,
  createdBy: String,
  createdAt: Date,
  updatedAt: Date,
  tags: [iYnTc,MRyks] //タグのid　
}
//この場合この記事はバスケとフットサルの記事であることを示す
```

バスケに関する記事の取得
```
let tags_id = iYnTc //バスケのid
db.collection("articles").where("tags", "array-contains", "tags_id")
```

>グラフ描画のための情報は入れちゃったほうが描画は楽だけど、
そうするとVolumeも入れないといけないからそこは要検討かも

確かに！しかしvolume入れるとなると更新数えげつないことになる問題よね🤔
ex..サッカー、バスケ、フットサルの全てが、スポーツとの関連趣味である場合、
tags/サッカー/relevance/スポーツ
tags/バスケ/relevance/スポーツ
tags/フットサル/relevance/スポーツ　の全部更新になる

**案①**
現状volume持たせるのは諦めて、relevanceだけにする。
**要するにこのまま！**
この場合、ノード表示においてvolumeの可視化は諦める

**案②**
時間は少しかかるかもだけどvolumeだけは　tags/趣味　から取ってくる

**Comment by Kattsuuya** [comment]
1日に1回更新するって話だったと思うから、よほどタグ数が増えない限り今の方針のままでいいと思う！

**Comment by Kattsuuya** [comment]
とりあえずこのissueはcloseして良いのだろうか
