### ISSUE TITLE
趣味のグラフが見られるようになりました

### ISSUE THREAD

**Issue by nanaka0012** [enpitut2020/Hobeeeeee#13]
## 概要

趣味の関連度合いをもとにしたグラフを表示する

## 関連issue

このPBLのSBL
- [x] : #14 
- [x] : #15 
- [x] : #16 
- [x] : #18 
- [x] : #19 
- [x] : #17 
- [x] : #45

## その他

これは**PBL**だよ

**Comment by mei28** [comment]
おわり！！！
