### ISSUE TITLE
グラフ描画のためにfirebaseからデータを取得できるようにする

### ISSUE THREAD

**Issue by mei28** [enpitut2020/Hobeeeeee#14]
## 概要

- #12 で決めたデータ構造からグラフ描画に使うデータを取得する機能を実装する
- 使うとしたら記事データ，規模感とか？

## 関連issue

- PBL: #13

**Comment by hotsukai** [comment]
これもクローズ??

**Comment by nanaka0012** [comment]
くろーず！
