### ISSUE TITLE
グラフページにただのテキストを表示

### ISSUE THREAD

**Issue by mei28** [enpitut2020/Hobeeeeee#15]
## 概要

- #14 でできた情報を取得する機能を使って，ひとまず1つ情報を描画(出力)する機能を実装してもらう．
- canvasで描画する必要はなく，firebaseからとってきた情報を表示するだけでよい

## 関連issue

- PBL: #13 
- SBL: #14 データを取得する

**Comment by hotsukai** [comment]
これクローズでいいんじゃない?

**Comment by nanaka0012** [comment]
クローズしちゃうね～
