### ISSUE TITLE
canvasで直打ちデータのグラフを表示する

### ISSUE THREAD

**Issue by nanaka0012** [enpitut2020/Hobeeeeee#16]
## 概要

canvasを使って、丸がぽんぽこしてるグラフを作る : [参考URL](https://sterfield.co.jp/designer/html5%E3%81%AEcanvas%E3%81%A7%E3%83%AC%E3%82%B9%E3%83%9D%E3%83%B3%E3%82%B7%E3%83%96%E3%81%AA%E3%83%AA%E3%83%B3%E3%82%AF-%E5%86%86%E5%BC%A7%E7%B7%A8/)
このissueではfirebaseのデータを使わなくていいので、直打ちデータでとりあえず動かしてみる
(hobeeeeeeで使ってるデータと同じ構成だと良い)

## 関連issue

PBL: #13

**Comment by mei28** [comment]
https://cr-vue.mio3io.com/examples/canvas.html#%E3%83%87%E3%83%A2

**Comment by mei28** [comment]
12/02の feature/#16/nodeCanvas -> develop で対応
