### ISSUE TITLE
ノード(描画オブジェクト)を複数表示

### ISSUE THREAD

**Issue by mei28** [enpitut2020/Hobeeeeee#17]
## 概要

- #18 でできた機能（たぶん1つ）を複数表示できるようにする．
- 加えて，ノードの大きさ，位置をしてい（最初はランダムでも）できるようにする．

## 関連issue

- PBL: #13 
- SBL: #18 1つ表示

**Comment by Kattsuuya** [comment]
このissueはノードの

- 位置
- 大きさ

を指定できたら完了だね
