### ISSUE TITLE
canvasの表示とfirebaseからのデータを組み合わせて表示する

### ISSUE THREAD

**Issue by nanaka0012** [enpitut2020/Hobeeeeee#18]
## 概要

#16 #14 #15 で、canvasで直打ちグラフ表示＆firebaseの接続が終わっているはずなので
canvasでfirebaseの情報をグラフ表示する

## 関連issue
PBL: #13 
SBL: #17 

## その他
もしこのissueの過程でノードの複数表示が一緒にできそうだったら #17 もやってほしい

**Comment by Kattsuuya** [comment]
これはもう満たしてるからcloseしてもよい？
