### ISSUE TITLE
firebaseのUtilsでのデータ構造変更

### ISSUE THREAD

**Issue by hotsukai** [enpitut2020/Hobeeeeee#26]
## 概要
firebaseUtilsにて趣味ノードを一括取得した際のデータを構造を変更したい。
また、それに伴いIDからデータを単体取得するUtilsも新規作成する。
## 詳細
現在はfirestoreから持ってきたデータをObjectのObjectとしている。([該当箇所コード](https://github.com/enpitut2020/hobeeeeee/blob/develop/plugins/firebaseUtils.js#L17))
```
{
  "2c2wNJ6adRJ8dHU7rRnG":{
      id : "2c2wNJ6adRJ8dHU7rRnG",
      title : "ファッション",
      volume : 10
    },
"mOuvsY2QvNrePwNNRfNl":{
      id : "mOuvsY2QvNrePwNNRfNlG",
      title : "スポーツ",
      volume : 11
    },
}
```
しかしこれではfor文で回す・ランダム取得・ソートなどが実装上やりにくい。そのため下記のようにObjectのArrayに変更したい。
```
[
  {
      id : "2c2wNJ6adRJ8dHU7rRnG",
      title : "ファッション",
      volume : 10
   },
  {
      id : "mOuvsY2QvNrePwNNRfNlG",
      title : "スポーツ",
      volume : 11
    },
]
```
## その他
もともとObjectのArrayではなくObjectのObjectにしたのは、IDからObjectの中身を取得しやすいから。
でもIDから中身のデータを持ってきたい場合は`get([ID])`(前述の単体取得するUtils)を使うべき。

**Comment by mei28** [comment]
#27  でグラフ側は対応

**Comment by mei28** [comment]
#30  で対応
