### ISSUE TITLE
自動デプロイの設定をする

### ISSUE THREAD

**Issue by Kattsuuya** [enpitut2020/Hobeeeeee#33]
## 概要
Netlifyで自動デプロイさせる設定をする。
レビュー（特にロングレビュー）のときにenPiTの人たちに触ってもらえる状態にしたほうが良い意見が貰えそう。

## 議論
個人的にはmainブランチをデプロイさせたい！
けど、devolopブランチでもいいと思う。
どちらにするかは話し合いたいです！

## 参考
[Vue.jsで実装したプロダクトのGithubレポジトリから自動デプロイさせる方法](https://cr-vue.mio3io.com/tutorials/netlify.html#github-%E3%81%8B%E3%82%89%E3%81%AE%E8%87%AA%E5%8B%95%E3%83%87%E3%83%97%E3%83%AD%E3%82%A4)

**Comment by mei28** [comment]
デプロイで指定できるブランチの指定が簡単に変えられるなら，通常レビュー(devブランチ),ロングレビュー(mainブランチ)みたいにすれば良さそう．
めんどくさかったらenPiT中はdevを常に使いつづけるとかでいいと思う．

**Comment by Kattsuuya** [comment]
デプロイ完了！
Netlifyは俺のGithubアカウントでサインアップした！
@Hotsukai Netlifyの存在教えてくれてありがとう😁

**Comment by mei28** [comment]
デプロイ先のURLをREADMEとかに書いといてー
