### ISSUE TITLE
記事一覧のタグ(ノード名)が表示されていない

### ISSUE THREAD

**Issue by mei28** [enpitut2020/Hobeeeeee#35]
## 概要

記事を読むを押した後の記事一覧画面でタグ名(ノード名)が表示されていない．
![image](https://user-images.githubusercontent.com/51149822/99958720-3c691f80-2dcd-11eb-8007-3f549b186c61.png)

## 関連issue
#34 らへんのリファクタリングでこのバグが起きてそう

## その他

デプロイしゅごい

**Comment by mei28** [comment]
#34 はまだマージされてないから，もっと前のリファクタリングでおかしくなってる？

**Comment by KindMaple** [comment]
#22 やったときに解決したはず！

**Comment by Kattsuuya** [comment]
アクセスするプロパティ名が違っていて今まで表示されてなかったけど、#34 で解決したはず！
