### ISSUE TITLE
グラフ画面でランダムなノードを描画する。

### ISSUE THREAD

**Issue by hotsukai** [enpitut2020/Hobeeeeee#50]

**Comment by hotsukai** [comment]
firebaseの仕様ランダムなレコードを取得するのが無理。
なので今はランダムが必要なとき(トップページからのスポーン)は全件取得してnuxt側でランダムにしてるんだけど、
グラフでランダムな2~3このために毎回これをするとヤバそう。なので

1. NuxtのRouteが変わったときに自動で動くMiddlewareを使ってNuxtStoreにtagsがあるか確認

1. なければ全件取得しNuxtStoreに登録。このとき並び順をランダムにしてもいいかも。
※具体的にはリロードするとStoreのデータは消える。
1. ランダムIDが必要のときはStoreを参照する
※nuxt storeのデータはfirestoreより古い可能性があるのでtagの詳細が必要なときはfirestoreを参照する

って方針でどうですか??

**Comment by Kattsuuya** [comment]
@Hotsukai いいと思う！

調べてみたら明示的にオフラインでのfirestoreアクセスができる方法もあるみたい。
どっちの方がいいかな？

以下、参考になりそうな記事
https://qiita.com/Bosch_san/items/e3e06acdb3c7b53553f2
https://qiita.com/que9/items/81764c4f0dbf8d3e87b8

**Comment by hotsukai** [comment]
@KindMaple そんな便利なものが!!!
ちょっとこれでやってみますね!
