### ISSUE TITLE
グラフが大きくなる(数が増える)と見切れ始める

### ISSUE THREAD

**Issue by mei28** [enpitut2020/Hobeeeeee#52]
## 概要

- ノードのサイズやキャンバスサイズが固定だから，見切れ始めている．
- 全体を縮小するような処理を書く必要ある？
- 現在の中心がキャンバスの真ん中ではなく，ウィンドウの真ん中だからキャンバスのサイズを基準に **リサイズ** を行えばいい？
- ノードの大きさを変更するより，全体をリサイズする実装が正しい -> 後々ノードの大きさに意味を持たせるため．

![image](https://user-images.githubusercontent.com/51149822/101918854-39639100-3c0d-11eb-805e-c3d7348645c9.png)

## 関連issue

- PBL: #13 

## その他

プロダクトの本質じゃないけど，ユーザからすると気持ち悪いから直して行きたい．

**Comment by mei28** [comment]
https://www.kabuku.co.jp/developers/how-to-enable-zoom-in-svg

svgをズーム，ピンチする時に使えそう？

**Comment by hotsukai** [comment]
[panGraphブランチ](https://github.com/enpitut2020/hobeeeeee/compare/feature/%2352/panGraph)でviewBoxをぐりぐりするデバッグ用コントローラー作ったんでこのissue触る人使ってみて!!
![image](https://user-images.githubusercontent.com/45584045/102154421-b5cfcb80-3ebc-11eb-8697-ccf6bef53ba0.png)

**Comment by mei28** [comment]
developマージしたのでクローズ
