### ISSUE TITLE
記事を書いた後などに記事をシェアするボタンをつける

### ISSUE THREAD

**Issue by mei28** [enpitut2020/Hobeeeeee#63]
## 概要

記事をSNS（e.g. Twitter, Line Slack, etc.）にシェアするボタンを付けたい．

使いたい場面は,
1. いい記事を広めたいとき, 2.(投稿したときに投稿した旨を広めたい)　ときの2つがあると思ってる．

1 を達成するためには記事詳細のところに(ずぶったのとなりとか？)に設置すればいいと思う．

2 を達成するには，記事投稿時にシェアする機能をつけるとできる．

ただ，この実装にするより，記事投稿後強制的に，書いた記事ページに遷移すれば1の機能だけでできるかなと考えている．

**現状は記事を書いた後トップページに遷移するけど，自分の中では投稿した記事に遷移するのが自然なんだけどどうですか？**

## 関連issue

- PBL: #62

**Comment by Kattsuuya** [comment]
投稿後は書いた記事ページに遷移するんでいいと思う！

**Comment by ryogo-niwa** [comment]
提案してるやり方、1だけで済むのすごくいいと思います！
2の実装少し手間かかりそうですし！
