### ISSUE TITLE
記事に対してコメント（匿名？）をつけたい！

### ISSUE THREAD

**Issue by mei28** [enpitut2020/Hobeeeeee#64]
## 概要

読んだ記事に対してコメントを付けれるようにしたい！

コメント主は完全匿名でもいいきもするし，ユーザ名を自分で付けれるのでもいいし，わかんない．

- （コメントに対してgood的なのも会ったら嬉しいのかもしれないけど優先度は低い（最底辺？））

## 関連issue

- PBL: #62

**Comment by Kattsuuya** [comment]
コメントは任意の名前にするに一票！
