### ISSUE TITLE
関連が少ないときにランダムノードを増やす

### ISSUE THREAD

**Issue by mei28** [enpitut2020/Hobeeeeee#66]
## 概要

関連が少ないときに，表示されるグラフがすくなくて寂しく感じる．
![image](https://user-images.githubusercontent.com/51149822/102679326-5a6e4800-41f2-11eb-991b-36c89f7131c4.png)

例えば関連ノードが10こいかのときは，全部合わせて10個になるようにランダムノードを増やす？
関連ノードがたくさんあるときは，ランダムノードは最低2こ表示も忘れない．

## 関連issue

- PBL: #59

**Comment by hotsukai** [comment]
関連ノードと同じようにArrayのどっか(末尾?)にPushにしといてclassで色だけ変えるのが楽そう(By @mei28 )

**Comment by mei28** [comment]
関連ノードが少ない時にランダムノードを増やす機能の実装が終わった．
多い時: randam3つ
![image](https://user-images.githubusercontent.com/51149822/103169495-77a0b780-487f-11eb-822b-7192dd48cb1c.png)

少ない時: 
![image](https://user-images.githubusercontent.com/51149822/103169478-5cce4300-487f-11eb-80ea-4fe1b50ca0e7.png)

**Comment by mei28** [comment]
ランダムノードの位置はGraphSvgないにハードコーディングしているのを直したいけど，直した方わかんない．．．

関連ノードにランダムノードを追加して計算を行いたいけど，どうすればいいですか！

**Comment by hotsukai** [comment]
## とりあえず円形に表示
`relativeNodes` Arrayのどっかにpushしといたらとりあえず円形には表示できそう。

## 色を変えるなどランダム独自のスタイルをつけたい。
1. pushするときにTagObjectに`isRandom`みたいなプロパティをつける  
2.  実際に`targetNode`の周りのノードを表示する[ここらへん](https://github.com/enpitut2020/Hobeeeeee/blob/develop/components/GraphSvg.vue#L72-L90)で
```
:class="{'randomTags' : node.isRandom"}
```
ってクラスをつける。

みたいな感じでどうでしょう???

**Comment by Kattsuuya** [comment]
isRandomプロパティがtrueの関連ノードにだけrandomTagsクラスのスタイルを適用するってこと？

**Comment by hotsukai** [comment]
じぶんが考えてたのはそうですね～!!
[このクラス](https://github.com/enpitut2020/Hobeeeeee/blob/develop/components/GraphSvg.vue#L396-L398)です。
