### ISSUE TITLE
記事投稿後，書いた記事に遷移する

### ISSUE THREAD

**Issue by mei28** [enpitut2020/Hobeeeeee#67]
## 概要

記事投稿後に，ホームページに遷移するのではなく，書いた記事に遷移するように変更する．

## 関連issue

SBL: #63

**Comment by mei28** [comment]
![image](https://user-images.githubusercontent.com/51149822/102703622-91a52d80-42b4-11eb-92e9-eb353d046dae.png)

109行目，registerArticle で初めて生成されるarticle.idを使いたいんだけど，どうすればいいの？

コメントアウトしているやつで動かすと idがnullになっているから109行目で作られるidを取得できていない．

**Comment by Kattsuuya** [comment]
registerArticle()の返り値が新しい記事のidになるように変更すれば良さそう
