### ISSUE TITLE
トップページにhobeeeeeeロゴを表示する

### ISSUE THREAD

**Issue by hotsukai** [enpitut2020/Hobeeeeee#73]
## 概要
現在はNuxtロゴが表示されている。
代わりになんかしらの画像やhobeeeeeeロゴほしいですよね。
あとファビコンも。
何を表示するかは要検討だけど個人的には[これ](https://enpit2020tkb.slack.com/files/U0138BX6TFF/F01GXGJ3W0P/hobbeeeeee_logo_animation.mp4)好き

**Comment by mei28** [comment]
朝やろうとして，やり方わからずそっと閉じたやつだ

**Comment by hotsukai** [comment]
@mei28 issueありましたっけ??

**Comment by mei28** [comment]
issue立てずにやめたからこのままで大丈夫

**Comment by mei28** [comment]
あのmp4をサイトの初めに流すやつって簡単にできるもの？
できたら自己満足度がめっちゃあがる

**Comment by hotsukai** [comment]
https://github.com/enpitut2020/hobeeeeee/tree/addLogo
Gifにするのが楽だと思います。一応できました。
何を表示するかをちゃんと同意していないのでPRはまだにしておきます。
