### ISSUE TITLE
スマホ版でグラフが拡大できない，移動ができない

### ISSUE THREAD

**Issue by mei28** [enpitut2020/Hobeeeeee#75]
## 概要

スマホ版でグラフが拡大，移動できない．
スクロール禁止したのが，原因かな？

## 関連issue

#59

**Comment by hotsukai** [comment]
EventListnerでやるのは結構ゴリゴリになりそう([これ](https://developer.mozilla.org/ja/docs/Web/API/Touch_events)でmouse操作と同じようなのを書くことになりそう)なので、画面幅が一定以下のときは

- コントローラーを表示
- そもそも縮小表示とかかなぁ
