### ISSUE TITLE
プロダクト名の表記ゆれをなくす

### ISSUE THREAD

**Issue by hotsukai** [enpitut2020/Hobeeeeee#78]
◎ Hobeeeeee!!
○  Hobeeeeee (!!が使えない場合)
×  hobeeeeee
×  hobbeeeeee

**Comment by hotsukai** [comment]
@mei28 @KindMaple @nanaka0012 @niwabarubossa @Kurorie 
これあちこち修正になりそうなので要注意です。

**Comment by mei28** [comment]
- [x] netlify
- [x] タイトル
- [ ]

**Comment by mei28** [comment]
たぶんおわった！！
