### ISSUE TITLE
リンタ・フォーマッタの導入

### ISSUE THREAD

**Issue by Kattsuuya** [enpitut2020/Hobeeeeee#79]
# 提案

今更かもしれないけどリンタ・フォーマッタを導入したいと思うんだけど、どうですか？
**`feature/linter_formatter`ブランチに設定ファイルとか置いてあるので、checkout & yarn installして試してみて！**

## メリット

プルリクのレビューとかのコストを軽減できる！

## デメリット

特にないと思う！
細かく設定すると面倒くさいくらい

## 使い方

- $ yarn lint
  - プロジェクト配下の全js,vueファイルの構文チェックをして、コンソールに表示する
- $ yarn lint-fix
  - プロジェクト配下の全js,vueファイルのコードを自動整形する（直せないやつはエラー内容がコンソールに表示される）
- VSCodeの拡張機能（ESLint, Prettier）
  - 右クリックで「ドキュメントのフォーマット」
  - `settings.json`に"editor.formatOnSave": trueを追加すると保存時に自動整形してくれる

## 構文チェックのルール

ほとんどデフォルトのものを使ってるから、「こっちのほうがいい！」ってのがあったらどんどんコメントしてほしいです！

**Comment by nanaka0012** [comment]
取り込んだPR出しといてあれなんだけど、prettierが強力すぎて、
lintだとほとんど何も指摘されないのにlint-fixすると一気に直されないですか？
あと、私の環境だとlint-fixすると改行コードに起因すると思われる、大量の何もない変更が発生してしまうので、各々の環境のどっかの設定を統一する必要がありそう(あとで調べてみます)

**Comment by Kattsuuya** [comment]
そのへんまだ理解しきれてないごめん😅
`.eslintrc.js`で公式推奨ルールをESLint→Prettierの順でかけるようにしていて、`.prettierrc.js`で個々のルールを上書きするような書き方にしてるんだけど、`yarn lint`コマンドのときにESLintしか実行してない感じになってるのかなぁ（完全に理解してない）

**Comment by nanaka0012** [comment]
- `.gitatttributes`を追加することでコミットするときに勝手にLFに変換される
- `.prettierrc.js`で`EndofLine:auto`を追加することで改行コードが無視されるわけではないけど、やってみた感じ鬼の直しがなくなったのでよしなにしてくれてそう
の対策で改行コード問題は良い感じになりそうな予感がしてるけど
なんだかまだPrettierとESLintがよくわかってないのでもうちょっと見てみます:D

**Comment by Kattsuuya** [comment]
ありがたや🙇‍♂️
