### ISSUE TITLE
feature-dbをdevelopにマージ

### ISSUE THREAD

**Issue by mei28** [enpitut2020/Hobeeeeee#9]
## 概要

- feature-dbできちんと動作すくか確認
- 11/13の変更分の作業feature-dbを~~feature~~ developブランチにマージ

## 関連issue

PBL:  #8

**Comment by Kattsuuya** [comment]
動作確認してマージしました！

**Comment by Kattsuuya** [comment]
マージした過程で関連ノード（3x3の円）を消した（というより関連ノードの格納の仕方がわからなかったから配列をからのままにした）んだけど、新しくissue立てたほうが良いのかな
それとも #17 で実現できるから後回しでいいかな

**Comment by nanaka0012** [comment]
たしかほとんどサンプルコードそのまま的なことをにわくんが言ってたような気がするので、改めてissueをたてるほどではない気がする🤔

**Comment by ryogo-niwa** [comment]
数を９個に調整するためのところです？
そこはレビューの見栄えのためだけだったので、全然消したままで大丈夫だと思います！
