### ISSUE TITLE
ノードの表示個数のmaxに制限をつけるべきか？

### ISSUE THREAD

**Issue by mei28** [enpitut2020/Hobeeeeee#91]
## 概要

![image](https://user-images.githubusercontent.com/51149822/104080904-6fc51800-526e-11eb-903b-c2ccbf65e488.png)

関連ノードが多すぎる時に，
- 処理が重い
- 収まりきれていない
- 多すぎて何を見ればいいかわからない　状況になっている．
- (多すぎる時にfirebaseのAPI制限に引っかかるかもしれない)
    -> 1/8-9 24kアクセスしている（1日50Kまで）
- 本当に関連してるか？って気持ちになる

そこで，表示個数の最大の制限をつけるべきか？という話が出た．

関連12個+ランダム3個ぐらいでいいのでは？

**Comment by Kattsuuya** [comment]
# 今日話したこと
## 全部表示する
### メリット
- 関連趣味を網羅しているので漏れがない
### デメリット
- 処理が重くなる
- 端っこまで見えない
- アクセス制限怖い
- 当初想定したユーザ体験と違うのでは

## 上位N件に絞る
### メリット
- 見やすい
- 情報量が多すぎないのでユーザの視覚的負担になりにくい
### デメリット
- 絞り方を工夫しないと関連が小さい趣味が全く表示されない事態になる

**Comment by nanaka0012** [comment]
色々考えてみて、個人的には**関連全部表示する**に一票かなぁというお気持ちになった🤔

懸念されることとしては、見た目と処理の2つの問題があると思って、

- 見た目 : 情報量エグくてUX違くない？問題
全部表示して、かつ、離して配置が一つの手かなと
ノードの間隔を空けて、あえて画面の中に収めずにすれば情報量が多すぎなくて当初のユーザー体験に近くなるし、端まで見たければズームアウトしてもらうのが良いかなぁ
これについてはとりあえず試してみるしか

- 処理 : API制限に引っかかる問題
料金表見たらむしろ課金すればいいのではって思った
https://firebase.google.com/pricing
成果発表会当日耐えるだけだったら1000円もかからなそう

**Comment by Kattsuuya** [comment]
>  ノードの間隔を空けて、あえて画面の中に収めずにすれば情報量が多すぎなくて当初のユーザー体験に近くなるし、端まで見たければズームアウトしてもらうのが良いかなぁ

たしかに。
グラフを移動・ズームできるようにしたから、全部表示で良いかも。

> 処理 : API制限に引っかかる問題

料金もそうだし、実装的にもキャッシュでどうにかなるか今一度検討したほうがいいね！

**Comment by mei28** [comment]
グラフの表示個数は全部にする！！！
