### ISSUE TITLE
同じタグ名を複数付与すると記事数が正常に増加しない

### ISSUE THREAD

**Issue by Kattsuuya** [enpitut2020/Hobeeeeee#99]
## 概要

"dup"ってタグを3つ付けた記事を1回投稿した結果↓
![image](https://user-images.githubusercontent.com/47709871/104403409-cd71a100-559b-11eb-8000-f64c3291b2b3.png)
![image](https://user-images.githubusercontent.com/47709871/104403427-d5314580-559b-11eb-8046-5967e5b6fb56.png)

タグの重複チェックを入れる必要がある？

**Comment by hotsukai** [comment]
追加時にバリデーションいれるのやります!
